### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by xzou999** [plctlab/v8-internals#22]
something wrong when git clone, the message:

Cloning into 'v8-internals'...
remote: Enumerating objects: 247, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 247 (delta 22), reused 14 (delta 14), pack-reused 198
Receiving objects: 100% (247/247), 48.14 MiB | 2.23 MiB/s, done.
Resolving deltas: 100% (115/115), done.
error: invalid path 'slides/Oilpan:V8中C++ 垃圾回收器.pdf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by lazyparser** [comment]
Thanks for reporting this issue. Please try again.
