### ISSUE TITLE
Ignition Bytecodes 文档还需要更新吗

### ISSUE THREAD

**Issue by thyecust** [plctlab/v8-internals#6]
指的是这个文档 https://github.com/lazyparser/v8-internals/blob/master/bytecodes.rst
orz看了一眼全是 TODO。看了一眼 v8 文档里好像没有字节码的 specification，这是这个中文文档暂时不更新的原因吗？还是说其实有英文文档只是没有时间写这个中文文档呢？
如果有人知道解决方法的话，感谢你的回复。我可以来补充这个中文文档。

**Comment by lazyparser** [comment]
啊，主要是因为一直在忙别的事情，咕了很久 😂

V8 的字节码是有些代码内文档可以看的。后续看懂了之后就忙着做RISC-V的 porting 和 upstream 了。

后续我看看小队中有没有同学能补上。

另外，欢迎PR～～

**Comment by thyecust** [comment]
thanks. 我去看看代码。
